import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import styles2 from "../styles/title.module.css";
import styles_smileys from "../styles/smileys.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Easemoji</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/wave.svg" />
        {/* <link
          href="https://fonts.googleapis.com/css2?family=Inter&display=optional"
          rel="stylesheet"
        /> */}
      </Head>
      {/* <style>
        @import
        url('https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap');
      </style> */}

      <div className={styles.projectStatus}>🚧 Work In Progress. 🚧</div>

      <div className={styles2.titleSection}>
        <div className={styles2.newTag}>BRAND NEW PROJECT</div>
        <div className={styles2.titlesectionContent}>
          <Image src="/wave.svg" alt="Wave image" width={80} height={80} />
          <h3>Welcome to Easemoji</h3>

          <p className={styles2.p}>
            Copying emoticons made easy. Click on the emoticon to
            <br />
            copy to clipboard. Built by{" "}
            <Link href="https://github.com/AnadyaNair">
              <a>@AnadyaNair</a>
            </Link>{" "}
            using{" "}
            <Link href="https://nextjs.org">
              <a>Next.js</a>
            </Link>
            .
            <br />
            You can star the project on{" "}
            <Link href="https://github.com/AnadyaNair/easemoji-app">
              <a>GitHub</a>
            </Link>{" "}
            and leave a review.
          </p>
        </div>
      </div>

      <div className={styles2.uppertagSection}>
        <ul>
          <Link href="#smileys">
            <a>
              <li>Smileys</li>
            </a>
          </Link>

          <span></span>

          <Link href="/">
            <a>
              <li>People</li>
            </a>
          </Link>

          <span></span>

          <Link href="/">
            <a>
              <li>Animals</li>
            </a>
          </Link>

          <span></span>

          <Link href="/">
            <a>
              <li>Objects</li>
            </a>
          </Link>

          <span></span>

          <Link href="/">
            <a>
              <li>Food</li>
            </a>
          </Link>

          <span></span>

          <Link href="/">
            <a>
              <li>Vehicles</li>
            </a>
          </Link>

          <span></span>

          <Link href="/">
            <a>
              <li>Symbols</li>
            </a>
          </Link>
        </ul>
      </div>

      <div className={styles2.headingContainer}>
        <h3 id="smileys">22 Smileys</h3>
      </div>

      <div className={styles_smileys.smileyDiv}>
        <ul>
          <li
            id="emoji"
            onClick={() => {
              navigator.clipboard.writeText(emoji.textContent);
            }}
          >
            😀
          </li>
          <span></span>
          <li
            id="emoji2"
            onClick={() => {
              navigator.clipboard.writeText(emoji2.textContent);
            }}
          >
            😁
          </li>
          <span></span>
          <li
            id="emoji3"
            onClick={() => {
              navigator.clipboard.writeText(emoji3.textContent);
            }}
          >
            😂
          </li>
          <span></span>
          <li
            id="emoji4"
            onClick={() => {
              navigator.clipboard.writeText(emoji4.textContent);
            }}
          >
            🤣
          </li>
          <span></span>
          <li
            id="emoji5"
            onClick={() => {
              navigator.clipboard.writeText(emoji5.textContent);
            }}
          >
            😃
          </li>
          <span></span>
          <li
            id="emoji6"
            onClick={() => {
              navigator.clipboard.writeText(emoji6.textContent);
            }}
          >
            😄
          </li>
          <span></span>
          <li
            id="emoji7"
            onClick={() => {
              navigator.clipboard.writeText(emoji7.textContent);
            }}
          >
            😅
          </li>
          <span></span>
          <li
            id="emoji8"
            onClick={() => {
              navigator.clipboard.writeText(emoji8.textContent);
            }}
          >
            😆
          </li>
          <span></span>
          <li
            id="emoji9"
            onClick={() => {
              navigator.clipboard.writeText(emoji9.textContent);
            }}
          >
            😉
          </li>
          <span></span>
          <li
            id="emoji10"
            onClick={() => {
              navigator.clipboard.writeText(emoji10.textContent);
            }}
          >
            😊
          </li>
          <span></span>
          <li
            id="emoji11"
            onClick={() => {
              navigator.clipboard.writeText(emoji11.textContent);
            }}
          >
            😋
          </li>
        </ul>

        <ul>
          <li
            id="emoji12"
            onClick={() => {
              navigator.clipboard.writeText(emoji12.textContent);
            }}
          >
            😎
          </li>
          <span></span>
          <li
            id="emoji13"
            onClick={() => {
              navigator.clipboard.writeText(emoji13.textContent);
            }}
          >
            😍
          </li>
          <span></span>
          <li
            id="emoji14"
            onClick={() => {
              navigator.clipboard.writeText(emoji14.textContent);
            }}
          >
            😘
          </li>
          <span></span>
          <li
            id="emoji15"
            onClick={() => {
              navigator.clipboard.writeText(emoji15.textContent);
            }}
          >
            🥰
          </li>
          <span></span>
          <li
            id="emoji16"
            onClick={() => {
              navigator.clipboard.writeText(emoji16.textContent);
            }}
          >
            😗
          </li>
          <span></span>
          <li
            id="emoji17"
            onClick={() => {
              navigator.clipboard.writeText(emoji17.textContent);
            }}
          >
            😙
          </li>
          <span></span>
          <li
            id="emoji18"
            onClick={() => {
              navigator.clipboard.writeText(emoji18.textContent);
            }}
          >
            😚
          </li>
          <span></span>
          <li
            id="emoji19"
            onClick={() => {
              navigator.clipboard.writeText(emoji19.textContent);
            }}
          >
            🙂
          </li>
          <span></span>
          <li
            id="emoji20"
            onClick={() => {
              navigator.clipboard.writeText(emoji20.textContent);
            }}
          >
            🤗
          </li>
          <span></span>
          <li
            id="emoji21"
            onClick={() => {
              navigator.clipboard.writeText(emoji21.textContent);
            }}
          >
            🤩
          </li>
          <span></span>
          <li
            id="emoji22"
            onClick={() => {
              navigator.clipboard.writeText(emoji22.textContent);
            }}
          >
            🤔
          </li>
        </ul>
      </div>
      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main> */}

      {/* <footer className={styles.footer}>
        <p>
          Star the project on{" "}
          <Link href="https://github.com/AnadyaNair/easemoji-app">
            <a>GitHub</a>
          </Link>
          and do leave a review!
        </p>
        <br />
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
