import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import styles2 from "../styles/title.module.css";
import styles_smileys from "../styles/smileys.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Easemoji</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter&display=optional"
          rel="stylesheet"
        />
      </Head>

      <div className={styles.projectStatus}>🚧 Work In Progress.</div>

      <div className={styles2.titleSection}>
        <h2>🏓 Easemoji</h2>
        <p className={styles2.p}>
          Copying emoticons made easy!
          <br />
          Built by{" "}
          <Link href="https://github.com/AnadyaNair">
            <a>@AnadyaNair</a>
          </Link>{" "}
          using{" "}
          <Link href="https://github.com/Vercel/next.js">
            <a>Nextjs</a>
          </Link>
        </p>
      </div>

      <div className={styles2.uppertagSection}>
        <ul>
          <Link href="/">
            <a>
              <li>Smileys</li>
            </a>
          </Link>

          <span></span>

          <Link href="/">
            <a>
              <li>People</li>
            </a>
          </Link>

          <span></span>

          <Link href="/">
            <a>
              <li>Animals</li>
            </a>
          </Link>

          <span></span>

          <Link href="/">
            <a>
              <li>Objects</li>
            </a>
          </Link>

          <span></span>

          <Link href="/">
            <a>
              <li>Food</li>
            </a>
          </Link>

          <span></span>

          <Link href="/">
            <a>
              <li>Vehicles</li>
            </a>
          </Link>

          <span></span>

          <Link href="/">
            <a>
              <li>Symbols</li>
            </a>
          </Link>
        </ul>
      </div>

      <div className={styles2.headingContainer}>
        <h3>Smileys</h3>
      </div>

      <div className={styles_smileys.smileyDiv}>
        <ul>
          <li>😀</li>
          <span></span>
          <li>😁</li>
          <span></span>
          <li>😂</li>
          <span></span>
          <li>🤣</li>
          <span></span>
          <li>😃</li>
          <span></span>
          <li>😄</li>
          <span></span>
          <li>😅</li>
          <span></span>
          <li>😆</li>
          <span></span>
          <li>😉</li>
        </ul>
      </div>
      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main> */}

      <footer className={styles.footer}>
        <p>
          Star the project on{" "}
          <Link href="https://github.com/AnadyaNair/easemoji-app">
            <a>GitHub</a>
          </Link>
          and do leave a review!
        </p>
        <br />
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </footer>
    </div>
  );
}
